[package]
name = "ic-pub-key-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
ic-secp256k1 = "0.2.0"
ic-ed25519 = "0.3.0"
k256 = "0.13.4"
icrc-ledger-types = "0.1.11"
pretty_assertions = "1.4.1"
elliptic-curve = { version = "0.13.8" }
hex = "0.4"
serde_json = "1.0.145"
serde = "1.0.223"
