[package]
name = "mkpubkey"
version = "0.1.0"
edition = "2024"

[dependencies]
ic-secp256k1 = { path = "vendor/ic-secp256k1/" }
icrc-ledger-types = "0.1.9"
pretty_assertions = "1.4.1"

elliptic-curve = { version = "0.13.8" }
hex = "0.4"
k256 = { path = "vendor/k256" }
