name: Prepare

description: Setup node and install dependencies

runs:
  using: composite
  steps:
    - name: Read .nvmrc
      shell: bash
      run: |
        # zizmor: ignore=github-env
        echo "NODE_VERSION=$(cat .nvmrc | tr -d 'v')" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
